import { getRoutePrefix } from '@/utils/route';

/**
 * 技术导航列表
 */
export const navigations = [
  // {
  //   id: 1,
  //   label: "我的关注",
  //   order: 0,
  //   icon: "fav",
  //   children: [],
  // },
  {
    id: 2,
    label: '前端框架',
    order: 1,
    icon: 'html5',
    children: [
      {
        title: 'vuejs',
        desc: '一款用于构建 Web 界面，易学易用，性能出色且功能丰富的框架。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/vuejs.svg',
        siteUrl: 'https://cn.vuejs.org/',
      },
      {
        title: 'react',
        desc: 'React 用于构建用户界面的 JavaScript 库',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/react.svg',
        siteUrl: 'https://react.docschina.org/',
      },
      {
        title: 'Angular',
        desc: 'AngularJS是一个开发动态Web应用的框架。它让你可以使用HTML作为模板语言并且可以通过扩展的HTML语法来使应用组件更加清晰和简洁。它的创新之处在于，通过数据绑定和依赖注入减少了大量代码，而这些都在浏览器端通过JavaScript实现，能够和任何服务器端技术完美结合。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/angular.svg',
        siteUrl: 'https://angular.io/',
      },
      {
        title: 'Svelte',
        desc: 'Cybernetically enhanced web apps',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/svelte.svg',
        siteUrl: 'https://svelte.dev/',
      },
      {
        title: 'preact',
        desc: '3kb 大小的 React 轻量、快速替代方案，拥有相同的现代 API。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/preact.svg',
        siteUrl: 'https://preactjs.com/',
      },
      {
        title: 'solidjs',
        desc: "Solid is a purely reactive library. It was designed from the ground up with a reactive core. It's influenced by reactive principles developed by previous libraries.",
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/solidjs.svg',
        siteUrl: 'https://www.solidjs.com/',
      },
      {
        title: 'vue-router',
        desc: 'Vue.js 的官方路由',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/vuejs.svg',
        siteUrl: 'https://router.vuejs.org/zh/',
      },
      {
        title: 'react-router',
        desc: 'React 官网路由',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/react-router.svg',
        siteUrl: 'https://reactrouter.com/',
      },
      {
        title: 'pinia',
        desc: '您将喜欢使用的 Vue 存储库，它允许您跨组件/页面共享状态。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/pinia.svg',
        siteUrl: 'https://pinia.vuejs.org/',
      },
      {
        title: 'vuex',
        desc: 'Vuex 是一个专为 Vue.js 应用程序开发的状态管理模式 + 库。它采用集中式存储管理应用的所有组件的状态，并以相应的规则保证状态以一种可预测的方式发生变化。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/vuejs.svg',
        siteUrl: 'https://vuex.vuejs.org/zh/',
      },
      {
        title: 'redux',
        desc: 'Redux 是 JavaScript 状态容器，提供可预测化的状态管理。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/redux.svg',
        siteUrl: 'https://redux.js.org/',
      },
      {
        title: 'Rematch',
        desc: 'Rematch 是 JavaScript 状态容器，在 Redux 的基础上构建并减少了样板代码和执行了一些最佳实践。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/rematch.svg',
        siteUrl: 'https://rematchjs.bootcss.com/',
      },
      {
        title: 'recoil',
        desc: 'React 状态管理库。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/recoil.svg',
        siteUrl: 'https://recoiljs.org/zh-hans/',
      },
      {
        title: 'nextjs',
        desc: 'Next.js 是一个用于生产环境的 React 框架。Next.js 为您提供生产环境所需的所有功能以及最佳的开发体验：包括静态及服务器端融合渲染、 支持 TypeScript、智能化打包、 路由预取等功能 无需任何配置。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/nextjs.svg',
        siteUrl: 'https://www.nextjs.cn/',
      },
      {
        title: 'nuxtjs',
        desc: 'nuxtjs 是混合式 Vue 框架。使用 Vue 3 构建您的下一个应用，体验混合渲染、强大的数据获取和新功能。 Nuxt 3 是一个开源框架，使 Web 开发变得简单而强大。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/nuxtjs.svg',
        siteUrl: 'https://www.nuxtjs.org.cn/',
      },
      {
        title: 'nuejs',
        desc: 'Nue 是一个更接近于底层的的框架，采用了极简主义和网络标准。它结构简洁，速度极快。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/framework/nuejs.png',
        siteUrl: 'https://nuejs.org/',
      },
    ],
  },
  {
    id: 3,
    label: '开发社区',
    order: 4,
    icon: 'question-answer',
    children: [
      {
        title: 'github',
        desc: 'GitHub是世界上最大的代码托管平台，超7千万开发者正在使用。GitHub中文社区，是国内领先的开源社区，是一个帮您发现GitHub上优质开源项目的地方。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/github.svg',
        siteUrl: 'https://github.com',
      },
      {
        title: 'gitee',
        desc: 'Gitee.com（码云） 是 OSCHINA.NET 推出的代码托管平台，支持 Git 和 SVN，提供免费的私有仓库托管。目前已有超过 800 万的开发者选择 Gitee。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/gitee.svg',
        siteUrl: 'https://gitee.com/',
      },
      {
        title: '掘金',
        desc: '掘金是面向全球中文开发者的技术内容分享与交流平台。我们通过技术文章、沸点、课程、直播等产品和服务，打造一个激发开发者创作灵感，激励开发者沉淀分享，陪伴开发者成长的综合类技术社区。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/juejin.svg',
        siteUrl: 'https://juejin.cn/',
      },
      {
        title: 'segmentfault-思否',
        desc: 'SegmentFault 思否是中国领先的开发者技术社区。我们以技术问答、技术专栏、技术课程、技术资讯为核心的产品形态，为开发者提供纯粹、高质的技术交流平台。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/segmentfault.svg',
        siteUrl: 'https://segmentfault.com/',
      },
      {
        title: 'stack overflow',
        desc: 'Stack Overflow is the largest, most trusted online community for developers to learn, share their programming knowledge, and build their careers.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/stackoverflow.svg',
        siteUrl: 'https://stackoverflow.com/',
      },
      {
        title: 'CSDN',
        desc: 'CSDN是全球知名中文IT技术交流平台,创建于1999年,包含原创博客、精品问答、职业培训、技术论坛、资源下载等产品服务,提供原创、优质、完整内容的专业IT技术开发社区.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/csdn.jpg',
        siteUrl: 'https://www.csdn.net/',
      },
      {
        title: '博客园',
        desc: '博客园是一个面向开发者的知识分享社区。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/cnblogs.svg',
        siteUrl: 'https://www.cnblogs.com/',
      },
      {
        title: '开源中国',
        desc: 'OSCHINA.NET 是目前领先的中文开源技术社区。我们传播开源的理念，推广开源项目，为 IT 开发者提供了一个发现、使用、并交流开源技术的平台',
        logoUrl: getRoutePrefix() + '/dashboard/logo/community/oschina.svg',
        siteUrl: 'https://www.oschina.net/',
      },
    ],
  },
  {
    id: 4,
    label: '实用工具',
    order: 5,
    icon: 'tools',
    children: [
      {
        title: 'Regex101',
        desc: 'regex101 是一个在线生成，测试及调试正则表达式的工具。支持测试多种语言(PCRE,Python2.7, ECMAScript(JavaScript),Java,Go等)的正则表达式解析，提供高亮匹配公式、正则解析步骤分析、匹配详情等功能。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/regex101.png',
        siteUrl: 'https://regex101.com/',
      },
      {
        title: '正则大全',
        desc: '在线正则大全',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/regexp-complete.png',
        siteUrl: 'https://any86.github.io/any-rule/',
      },
      {
        title: 'TinyPNG',
        desc: '让你的网站更快，节省带宽。TinyPNG将您的WebP、PNG和JPEG图像优化50-80%，同时保持完全透明！',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/tinypng.png',
        siteUrl: 'https://tinypng.com/',
      },
      {
        title: '纯色占位图',
        desc: 'dummyimage 是一款生成纯色的在线占位图片工具网站。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/dummyimage.png',
        siteUrl: 'https://dummyimage.com/',
      },
      {
        title: 'RegExr正则学习',
        desc: '带有语法高亮的、支持PHP / PCRE 和 JS 语言、 上下文解释、 备忘单、参考 和 正则表达式社区的正则表达式测试工具',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/regexr.png',
        siteUrl: 'https://regexr-cn.com/',
      },
      {
        title: 'JSON格式化',
        desc: '提供相关的Json解析、验证、格式化、压缩、编辑器以及Json与XML相互转换等服务',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/json-cn.jpeg',
        siteUrl: 'https://www.json.cn/',
      },
      {
        title: 'JSON转Typescript',
        desc: '立即从JSON生成TypeScript接口。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/quicktype.svg',
        siteUrl: 'https://quicktype.io/typescript',
      },
      {
        title: 'codeif命名神器',
        desc: '从Github、Bitbucket、Google Code、Codeplex、Sourceforge、Fedora Project、GitLab中搜索项目，以查找实际使用变量名。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/codelf.jpg',
        siteUrl: 'https://unbug.github.io/codelf/',
      },
      {
        title: 'Convertio文件转换器',
        desc: 'Convertio - 在线转换文件的简单工具。支持超过309种不同的文档、图像、电子表格、电子书、文档、演示文稿、音频和视频格式。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/convertio.svg',
        siteUrl: 'https://convertio.co/zh/',
      },
      {
        title: 'png转ico',
        desc: '轻松将 PNG 图像转换为 ICO 格式！ 这个免费的转换器将使您能够快速将任何.png图像转换为.ico格式，而不会降低质量。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/pngtoicon.jpg',
        siteUrl: 'https://pngtoicon.com/cn',
      },
      {
        title: '免费图床',
        desc: '简单易操作，免费且不压缩图片画质的公共图床平台，支持对接PicGo。从本地相册选取图片上传到图床服务器快速获取图片外链。支持批量上传！',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/imgtp.jpg',
        siteUrl: 'https://www.imgtp.com/',
      },
      {
        title: '百度脑图',
        desc: '百度脑图，便捷的脑图编辑工具 - 控制创意，如此简单。让您在线上直接创建、保存并分享你的思路。免安装 云存储 易分享 体验舒适 功能丰富',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/naotu.png',
        siteUrl: 'https://naotu.baidu.com/',
      },
      {
        title: 'processOn',
        desc: 'ProcessOn是一个在线协作绘图平台，为用户提供强大、易用的作图工具！支持在线创作流程图、思维导图、组织结构图、网络拓扑图、BPMN、UML图、UI界面原型设计、iOS界面原型设计等。同时依托于互联网实现了人与人之间的实时协作和共享。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/processon.svg',
        siteUrl: 'https://www.processon.com/',
      },
      {
        title: 'linux命令搜索',
        desc: 'Linux命令搜索引擎:最专业的Linux命令大全，内容包含Linux命令手册、详解、学习，值得收藏的Linux命令速查手册。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/wangchujiang.svg',
        siteUrl: 'https://wangchujiang.com/linux-command/',
      },
      {
        title: 'Can I Use',
        desc: '"Can I use" provides up-to-date browser support tables for support of front-end web technologies on desktop and mobile web browsers.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/caniuse.png',
        siteUrl: 'https://caniuse.com/',
      },
      {
        title: '30 seconds of code',
        desc: 'Browse 1157 short code snippets for all your development needs on 30 seconds of code.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/tools/30secondsofcode.png',
        siteUrl: 'https://www.30secondsofcode.org/',
      },
    ],
  },
  {
    id: 5,
    label: '图片资源',
    order: 7,
    icon: 'image',
    children: [
      {
        title: '雪碧图生成器',
        desc: 'Generate CSS image sprites from multiple images with our easy-to-use uploading tool. Get started for free.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/image/toptal.svg',
        siteUrl: 'https://www.toptal.com/developers/css/sprite-generator',
      },
      {
        title: 'Lorem Picsum',
        desc: 'Lorem Ipsum... but for photos.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/image/picsum.svg',
        siteUrl: 'https://picsum.photos/',
      },
      {
        title: 'pexels',
        desc: '免费素材图片和视频，可以在任何地方使用。✓ 高质量 ✓ 100% 免费✓ 无需注明归属',
        logoUrl: getRoutePrefix() + '/dashboard/logo/image/pexels.svg',
        siteUrl: 'https://www.pexels.com/zh-cn/',
      },
      {
        title: 'unsplash',
        desc: '好看的免费图片和照片，你可以下载并用于任何项目。比任何免版税或库存照片都要好。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/image/unsplash.svg',
        siteUrl: 'https://unsplash.com/',
      },
    ],
  },
  {
    id: 6,
    label: '代码平台',
    order: 6,
    icon: 'code',
    children: [
      {
        title: 'CodeSandbox',
        desc: 'CodeSandbox is a cloud development platform that empowers developers to code, collaborate and ship projects of any size from any device in record time.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/code/codesandbox.svg',
        siteUrl: 'https://codesandbox.io/',
      },
      {
        title: 'CodePen',
        desc: 'An online code editor, learning environment, and community for front-end web development using HTML, CSS and JavaScript code snippets, projects, and web applications.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/code/codepen.svg',
        siteUrl: 'https://codepen.io/',
      },
      {
        title: 'StackBlitz',
        desc: 'Stay in the flow with instant dev experiences. No more hours stashing/pulling/installing locally — just click, and start coding.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/code/stackblitz.svg',
        siteUrl: 'https://stackblitz.com/',
      },
      {
        title: 'PlayCode',
        desc: 'The #1 JavaScript playground and sandbox to write, run and repl it. JavaScript playground is perfect for learning and prototyping javascript sandboxes. Fast. Easy to use.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/code/playcode.svg',
        siteUrl: 'https://playcode.io/',
      },
    ],
  },
  {
    id: 7,
    label: '设计资源',
    order: 12,
    icon: 'palette',
    children: [
      {
        title: 'Free Vector Illustra',
        desc: '免费下载设计素材-图标、照片、用户体验插图和视频音乐',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/icons8.png',
        siteUrl: 'https://icons8.com/illustrations',
      },
      {
        title: '传统中国色',
        desc: '提供各种中国的传统颜色的名称，CMYK值，RGB值，16进制表示。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/zhongguose.png',
        siteUrl: 'http://zhongguose.com/',
      },
      {
        title: '渐变色(WebGradients)',
        desc: '访问 WebGradients.com，了解 CSS3、Photoshop 和 Sketch 中的 180 种漂亮的线性渐变。 该系列由顶级设计师策划，完全免费。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/webgradients.png',
        siteUrl: 'https://webgradients.com/',
      },
      {
        title: '渐变色(uigradients)',
        desc: '为设计师和开发人员精心挑选的漂亮颜色渐变系列',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/uigradients.svg',
        siteUrl: 'https://uigradients.com/',
      },
      {
        title: '豆皮儿UI',
        desc: 'doupir豆皮儿网是一个专注于UI领域的垂直素材资源共享平台，旨在为UI设计师提供基础UI设计素材，并逐步打造成为一个垂直的素材交流平台。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/doupir.svg',
        siteUrl: 'https://www.doupir.com/',
      },
      {
        title: 'dribbble',
        desc: '在 Dribbble 上寻找顶级设计师和创意专业人士。 我们是设计师获得灵感、反馈、社区和工作的地方。 您发现并与全球设计师联系的最佳资源。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/dribbble.svg',
        siteUrl: 'https://dribbble.com/',
      },
      {
        title: '色盘',
        desc: ' Hey Designers & Developers! We have a set of tools that include Material Color Palette, Flat UI Color Palette, Icons, Unicodes & more.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/materialui.svg',
        siteUrl: 'https://materialui.co/',
      },
      {
        title: '色轮(adobe color)',
        desc: '使用色轮或影像建立调色盘，或浏览 Adobe Color 社群中的数千个颜色组合。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/adobe-color.png',
        siteUrl: 'https://color.adobe.com/zh/create/color-wheel',
      },
      {
        title: '美叶 - 优质灵感辑录',
        desc: '美叶，为设计师，创意人提供有价值的设计参考。灵感采集，优质素材获取，时刻Follow最新流行设计趋势',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/meiye.png',
        siteUrl: 'https://www.meiye.art/',
      },
      {
        title: '站酷ZCOOL',
        desc: '站酷ZCOOL，中国设计师互动平台。深耕设计领域十五年，站酷聚集了1500万设计师、摄影师、插画师、艺术家、创意人，设计创意群体中具有较高的影响力与号召力。。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/zcool.svg',
        siteUrl: 'https://www.zcool.com.cn/',
      },
      {
        title: '花瓣网',
        desc: '花瓣网, 设计师寻找灵感的天堂！图片素材领导者，帮你采集、发现网络上你喜欢的事物。你可以用它收集灵感,保存有用的素材,计划旅行,晒晒自己想要的东西',
        logoUrl: getRoutePrefix() + '/dashboard/logo/palette/huaban.svg',
        siteUrl: 'https://huaban.com/',
      },
    ],
  },
  {
    id: 8,
    label: '在线设计',
    order: 13,
    icon: 'paint',
    children: [
      {
        title: '稿定设计',
        desc: '在线快速图片和视频编辑,不会PS也能搞定设计。海报、简历、PPT、公众号配图、电商等海量模板快速出图。三秒抠图实用便捷,抖音快手热门视频轻松搞定。海量正版授权资源,商用无忧。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/gaoding.svg',
        siteUrl: ' https://www.gaoding.com/',
      },
      {
        title: '即时设计',
        desc: '即时设计是一款在线可协作的UI设计工具，是可协作的在线sketch、国内版figma，拥有海量的设计资源与素材，支持导入sketch格式的源文件。支持创建交互原型、获取设计标注、快速切图、团队协作等工作。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/js-design.svg',
        siteUrl: 'https://js.design/',
      },
      {
        title: 'Pixso',
        desc: 'Pixso是一体化设计协作工具，助力产研设团队制作原型，UI/UX设计，视觉设计，低代码交付时获得更轻松流畅的工作体验，让团队协作更高效。支持Sketch，Figma格式。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/pixso.png',
        siteUrl: 'https://pixso.cn/',
      },
      {
        title: 'figma',
        desc: '作为一个团队打造更好的产品。 使用 Figma 将设计、原型制作和收集反馈集中在一处。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/figma.svg',
        siteUrl: 'https://www.figma.com/',
      },
      {
        title: 'MasterGo',
        desc: 'MasterGo 是为团队协作而生的一站式在线产品设计工具,提供在线产品设计、原型图制作设计、网页开发设计、产品交互设计、UI和UX设计工具等功能,支持多人实时协作,可快速搭建设计系统,为产品设计师、交互设计师、工程师以及产品经理提供更简单灵活的工作模式。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/mastergo.svg',
        siteUrl: 'https://mastergo.com/',
      },
      {
        title: '墨刀',
        desc: '墨刀是A股上市公司万兴科技旗下的产品设计一体化在线协同办公平台,集原型设计,线上版sketch设计师工具、流程图、思维导图为一体，支持团队项目实时协作和管理，金融级数据安全保障，还支持私有化部署，是设计师、产品经理和技术开发团队必备工具。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/paint/modao.svg',
        siteUrl: 'https://modao.cc/',
      },
    ],
  },
  {
    id: 9,
    label: '图标库',
    order: 8,
    icon: 'smile',
    children: [
      {
        title: 'IconFont',
        desc: 'iconfont-国内功能很强大且图标内容很丰富的矢量图标库，提供矢量图标下载、在线存储、格式转换等功能。阿里巴巴体验团队倾力打造，设计和前端开发的便捷工具',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/iconfont.svg',
        siteUrl: 'https://www.iconfont.cn/',
      },
      {
        title: 'IconPark',
        desc: 'IconPark, park your icon. Made by ByteDance',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/iconpark.svg',
        siteUrl: 'https://iconpark.oceanengine.com/official',
      },
      {
        title: 'SimpleIcons',
        desc: '2434 Free SVG icons for popular brands',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/simpleicons.svg',
        siteUrl: 'https://simpleicons.org/',
      },
      {
        title: 'RemixIcon',
        desc: 'Remix Icon 是一组为设计师和开发人员精心打造的开源中性风格系统符号；所有图标均可免费用于个人和商业用途。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/remixicon.svg',
        siteUrl: 'https://remixicon.com/',
      },
      {
        title: 'FontAwesome',
        desc: "The internet's icon library + toolkit. Used by millions of designers, devs, & content creators. Open-source. Always free. Always awesome.",
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/fontawesome.svg',
        siteUrl: 'https://fontawesome.com/',
      },
      {
        title: 'BootstrapIcon',
        desc: 'Free, high quality, open source icon library with over 1,800 icons. Include them anyway you like—SVGs, SVG sprite, or web fonts. Use them with or without Bootstrap in any project.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/bootstrapicon.svg',
        siteUrl: 'https://icons.getbootstrap.com/',
      },
      {
        title: 'MaterialIcons',
        desc: '谷歌提供符合 Material 设计规范的免费图标库，Material Symbols 是我们最新的图标，将 2,500 多个字形整合到一个字体文件中，并具有多种设计变体。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/materialicons.svg',
        siteUrl: 'https://fonts.google.com/icons',
      },
      {
        title: 'xicons',
        desc: 'SVG Vue/React components integrated from fluentui-system-icons, ionicons, ant-design-icons, material-design-icons, Font-Awesome, tabler-icons and carbon icons. (Vue3, Vue2, React, SVG)',
        logoUrl: getRoutePrefix() + '/dashboard/logo/smile/xicons.png',
        siteUrl: 'https://www.xicons.org/',
      },
    ],
  },
  {
    id: 10,
    label: '开发文档',
    order: 3,
    icon: 'document',
    children: [
      {
        title: 'es6入门教程',
        desc: '《ECMAScript 6 入门教程》是一本开源的 JavaScript 语言教程，全面介绍 ECMAScript 6 新引入的语法特性。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/yuanyifeng.jpeg',
        siteUrl: 'https://es6.ruanyifeng.com/',
      },
      {
        title: '现代 JavaScript 教程',
        desc: '以最新的 JavaScript 标准为基准。通过简单但足够详细的内容，为你讲解从基础到高阶的 JavaScript 相关知识。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/javascript-info.svg',
        siteUrl: 'https://zh.javascript.info/',
      },
      {
        title: 'MDN Web Docs',
        desc: 'MDN Web Docs网站提供了有关开放式Web技术的信息，包括用于网站和渐进式Web应用程序的HTML、CSS和API。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/MDN.svg',
        siteUrl: 'https://developer.mozilla.org/zh-CN/',
      },
      {
        title: '菜鸟教程',
        desc: '菜鸟教程(www.runoob.com)提供了编程的基础技术教程, 介绍了HTML、CSS、Javascript、Python，Java，Ruby，C，PHP , MySQL等各种编程语言的基础知识。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/runoob.png',
        siteUrl: 'https://www.runoob.com/',
      },
      {
        title: 'Typescript',
        desc: 'TypeScript通过向语言中添加类型来扩展JavaScript，在运行代码之前捕捉错误并提供修复来加速开发体验。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/ts.svg',
        siteUrl: 'https://www.typescriptlang.org/',
      },
      {
        title: 'TypeScript 入门教程',
        desc: '从 JavaScript 程序员的角度总结思考，循序渐进的理解 TypeScript。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/ts.svg',
        siteUrl: 'https://ts.xcatliu.com/',
      },
      {
        title: 'vuepress',
        desc: 'Vue 驱动的静态网站生成器',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/vuepress.png',
        siteUrl: 'https://vuepress.vuejs.org/zh/',
      },
      {
        title: 'vitpress',
        desc: 'Vite & Vue powered static site generator.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/document/vitepress.jpeg',
        siteUrl: 'https://vitepress.vuejs.org/',
      },
    ],
  },
  {
    id: 11,
    label: '跨平台',
    order: 9,
    icon: 'terminal',
    children: [
      {
        title: 'electron',
        desc: '使用 JavaScript，HTML 和 CSS 构建跨平台的桌面应用程序。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/terminal/electron.svg',
        siteUrl: 'https://www.electronjs.org/',
      },
      {
        title: 'flutter',
        desc: 'Flutter 官方文档中文版，包含 SDK 下载、最新特性介绍、代码示例、开发文档、中文社区等内容。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/terminal/flutter.svg',
        siteUrl: 'https://flutter.cn/',
      },
      {
        title: 'tauri',
        desc: 'Tauri是一个框架，用于为所有主要桌面平台构建小巧、快速的二进制文件。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/terminal/tauri.svg',
        siteUrl: 'https://tauri.app/',
      },
    ],
  },
  {
    id: 12,
    label: 'UI 组件库',
    order: 2,
    icon: 'ui-components',
    children: [
      {
        title: 'Material-UI',
        desc: 'React 组件用于更快速、更简便的 web 开发。你也可以建立你自己的设计系统，或者从 Material Design 开始。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/mui.svg',
        siteUrl: 'https://v4.mui.com/zh/',
      },
      {
        title: 'Ant Design',
        desc: 'antd 是基于 Ant Design 设计体系的 React UI 组件库，主要用于研发企业级中后台产品。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/antd.svg',
        siteUrl: 'https://ant.design/docs/react/introduce-cn',
      },
      {
        title: 'Ant Design Mobile',
        desc: 'Ant Design Mobile 探索移动端 Web 的体验极限',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/antd-mobile.svg',
        siteUrl: 'https://mobile.ant.design/zh',
      },
      {
        title: 'Ant Design Vue',
        desc: '基于Ant设计和Vue的企业级UI组件',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/antd-vue.svg',
        siteUrl: 'https://www.antdv.com/docs/vue/introduce-cn',
      },
      {
        title: 'Ant Motion',
        desc: '使用 Ant Motion 能够快速在 React 框架中使用动画。我们提供了单项，组合动画，以及整套解决方案。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/antd-motion.svg',
        siteUrl: 'https://motion.ant.design/index-cn',
      },
      {
        title: 'Chakra-UI',
        desc: 'Chakra UI is a simple, modular and accessible component library that gives you the building blocks you need to build your React applications.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/chakra.svg',
        siteUrl: 'https://chakra-ui.com/',
      },
      {
        title: 'Mantine',
        desc: 'Build fully functional accessible web applications faster than ever – Mantine includes more than 100 customizable components and 40 hooks to cover you in any situation',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/mantine.svg',
        siteUrl: 'https://mantine.dev/',
      },
      {
        title: 'elemnt plus',
        desc: '基于 Vue 3，面向设计师和开发者的组件库',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/element-plus.svg',
        siteUrl: 'https://element-plus.gitee.io/zh-CN/',
      },
      {
        title: 'element',
        desc: 'Element，一套为开发者、设计师和产品经理准备的基于 Vue 2.0 的桌面端组件库',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/element.svg',
        siteUrl: 'https://element.eleme.cn/#/zh-CN',
      },
      {
        title: 'naive ui',
        desc: 'Naive UI 是一个 Vue3 的组件库。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/naive.svg',
        siteUrl: 'https://www.naiveui.com/zh-CN/os-theme',
      },
      {
        title: 'TDesign',
        desc: 'TDesign 是腾讯开源的企业级设计体系，提供了统一价值观，一致的设计语言和视觉风格，和开箱即用的 UI 组件库。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/tdesign.svg',
        siteUrl: 'https://tdesign.tencent.com/',
      },
      {
        title: 'arco design',
        desc: 'Arco Design - 企业级产品的完整设计和开发解决方案',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/arco-design.svg',
        siteUrl: 'https://arco.design/',
      },
      {
        title: 'arco design mobile',
        desc: '让移动应用获得开箱即用的设计解决方案',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/arco-design.svg',
        siteUrl: 'https://arco.design/mobile/react',
      },
      {
        title: 'semi design',
        desc: '由抖音前端与 UED 团队维护，易于定制的现代化设计系统，帮助设计师与开发者打造高质量产品。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/semi-design.svg',
        siteUrl: 'https://semi.design/zh-CN/',
      },
      {
        title: 'vuetify',
        desc: 'Vuetify 是一个material风格的 Vue UI 库，包含手工制作的精美材料组件。不需要设计技能 - 创建令人惊叹的应用程序所需的一切都触手可及。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/ui-components/vuetify.png',
        siteUrl: 'https://vuetify.cn/zh-Hans/',
      },
    ],
  },
  {
    id: 13,
    label: '数据可视化',
    order: 10,
    icon: 'chart',
    children: [
      {
        title: 'antv',
        desc: 'AntV 是蚂蚁集团全新一代数据可视化解决方案，致力于提供一套简单方便、专业可靠、无限可能的数据可视化最佳实践。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/chart/antv.svg',
        siteUrl: 'https://antv.vision/zh',
      },
      {
        title: 'Echarts',
        desc: 'Apache ECharts，一款基于JavaScript的数据可视化图表库，提供直观，生动，可交互，可个性化定制的数据可视化图表。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/chart/echarts.png',
        siteUrl: 'https://echarts.apache.org/zh/index.html',
      },
      {
        title: 'd3js',
        desc: 'D3 is a JavaScript library for visualizing data with HTML, SVG, and CSS.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/chart/d3js.svg',
        siteUrl: 'https://d3js.org/',
      },
    ],
  },
  {
    id: 14,
    label: '打包构建',
    order: 11,
    icon: 'build',
    children: [
      {
        title: 'webpack',
        desc: 'webpack 主要目的是编译打包 JavaScript 文件以在浏览器中使用，但它也能够转换、捆绑或打包几乎任何资源或资产。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/webpack.svg',
        siteUrl: 'https://webpack.js.org/',
      },
      {
        title: 'rollup',
        desc: 'Rollup 是一个 JavaScript 模块打包器，可以将小块代码编译成大块复杂的代码，Rollup 对代码模块使用新的标准化格式，这些标准都包含在 JavaScript 的 ES6 版本中。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/rollup.png',
        siteUrl: 'https://www.rollupjs.com/',
      },
      {
        title: 'vite',
        desc: '下一代的前端工具链，为开发提供极速响应。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/vite.svg',
        siteUrl: 'https://cn.vitejs.dev/',
      },
      {
        title: 'esbuild',
        desc: 'esbuild - 极速 JavaScript 打包器',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/esbuild.svg',
        siteUrl: 'https://esbuild.docschina.org/',
      },
      {
        title: 'Turbopack',
        desc: 'Turbopack 是一个可以取代 Webpack 的新开源打包工具，使用 Rust 编写，针对 JavaScript 和 TypeScript 进行了优化。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/turbopack.svg',
        siteUrl: 'https://rolldown.rs/',
      },
      {
        title: 'Rolldown',
        desc: 'Rolldown 可以看作是 Rollup 的替代品。它提供与 Rollup 兼容的应用程序接口和插件接口，使用 Rust 编写，作为 Vite 未来使用的打包工具',
        logoUrl: getRoutePrefix() + '/dashboard/logo/build/rolldown.svg',
        siteUrl: 'https://rolldown.rs/',
      },
    ],
  },
  {
    id: 15,
    label: 'Node 相关',
    order: 14,
    icon: 'node',
    children: [
      {
        title: 'nodejs',
        desc: "Node.js® is a JavaScript runtime built on Chrome's V8 JavaScript engine.",
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/node.svg',
        siteUrl: 'https://nodejs.org/en/docs/',
      },
      {
        title: 'express',
        desc: '高度包容、快速而极简的 Node.js Web 框架',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/express.png',
        siteUrl: 'https://expressjs.com/zh-cn/',
      },
      {
        title: 'koa',
        desc: '基于 Node.js 平台的下一代 web 开发框架',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/koa.png',
        siteUrl: 'https://www.koajs.com.cn/',
      },
      {
        title: 'eggjs',
        desc: 'Egg.js 为企业级框架和应用而生，我们希望由 Egg.js 孕育出更多上层框架，帮助开发团队和开发人员降低开发和维护成本。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/egg.svg',
        siteUrl: 'https://www.eggjs.org/zh-CN',
      },
      {
        title: 'nestjs',
        desc: 'NestJS是一个用于构建高效、可扩展节点的框架。js web应用程序。它使用现代JavaScript，使用TypeScript构建，并结合了OOP（面向对象编程）、FP（函数式编程）和FRP（函数式反应式编程）的元素。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/nest.svg',
        siteUrl: 'https://nestjs.com/',
      },
      {
        title: 'typeorm',
        desc: 'TypeORM is an ORM that can run in NodeJS, Browser, Cordova, PhoneGap, Ionic, React Native, NativeScript, Expo, and Electron platforms and can be used with TypeScript and JavaScript ',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/typeorm.png',
        siteUrl: 'https://typeorm.io/',
      },
      {
        title: 'Sequelize',
        desc: 'Sequelize是一种现代类型脚本和节点。用于Postgres、MySQL、MariaDB、SQLite和SQL Server等的js ORM。具有可靠的事务支持、关系、即时和延迟加载、读取复制等功能。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/sequelize.svg',
        siteUrl: 'https://sequelize.org/',
      },
      {
        title: 'prisma',
        desc: 'Next-generation Node.js and TypeScript ORM',
        logoUrl: getRoutePrefix() + '/dashboard/logo/node/prisma.png',
        siteUrl: 'https://www.prisma.io/',
      },
    ],
  },
  {
    id: 16,
    label: '小程序相关',
    order: 15,
    icon: 'miniprogram',
    children: [
      {
        title: '微信小程开发文档',
        desc: '微信开发者平台文档',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/weixin.svg',
        siteUrl: 'https://developers.weixin.qq.com/miniprogram/dev/framework/',
      },
      {
        title: '支付宝小程序',
        desc: '支付宝小程序官网',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/alipay.svg',
        siteUrl: 'https://opendocs.alipay.com/mini',
      },
      {
        title: 'QQ小程序',
        desc: 'QQ小程序是连接年轻用户的新方式，覆盖8亿新生代活跃网民。轻便快捷的开发模式，将能在QQ内被轻松获取和传播',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/qq.svg',
        siteUrl: 'https://q.qq.com/miniapp',
      },
      {
        title: 'uni-app',
        desc: 'uni-app多端开发,开发一次同时生成App、小程序、H5',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/uni-app.png',
        siteUrl: 'https://uniapp.dcloud.net.cn/',
      },
      {
        title: 'taro',
        desc: 'Taro 是一个开放式跨端跨框架解决方案，支持使用 React/Vue/Nerv 等框架来开发 微信 / 京东 / 百度 / 支付宝 / 字节跳动 / QQ / 飞书 小程序 / H5 / RN 等应用。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/taro.png',
        siteUrl: 'https://taro-docs.jd.com/taro/docs/',
      },
      {
        title: 'kbone',
        desc: 'kbone 是一个致力于微信小程序和 Web 端同构的解决方案。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/miniprogram/kbone.svg',
        siteUrl: 'https://wechat-miniprogram.github.io/kbone/docs',
      },
    ],
  },
  {
    id: 17,
    label: '办公协作',
    order: 17,
    icon: 'office',
    children: [
      {
        title: '语雀',
        desc: '十万阿里人都在用的笔记与文档知识库',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/yuque.svg',
        siteUrl: 'https://www.yuque.com/dashboard',
      },
      {
        title: '腾讯文档',
        desc: '腾讯文档是一款可多人协作的在线文档，可同时编辑Word、Excel和PPT文档，云端实时保存。可针对QQ、微信好友设置文档访问、编辑权限，支持多种版本Word、Excel和PPT文档模板。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/qq.svg',
        siteUrl: 'https://docs.qq.com/',
      },
      {
        title: '飞书',
        desc: '飞书——先进企业协作与管理平台。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/feishu.png',
        siteUrl: 'https://www.feishu.cn/',
      },
      {
        title: '腾讯会议',
        desc: '基于腾讯20多年音视频通讯经验，腾讯会议提供一站式音视频会议解决方案，让您能随时随地体验高清流畅的会议以及会议协作。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/tencent-meeting.png',
        siteUrl: 'https://meeting.tencent.com/',
      },
      {
        title: 'google文档',
        desc: '使用 Google 文档创建和协作处理在线文档。在任意设备上安全地实时共享内容，与他人一起编辑文档。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/google.png',
        siteUrl: 'https://www.google.com/intl/zh-CN/docs/about/',
      },
      {
        title: '石墨文档',
        desc: '全新一代云端 Office，面向未来的办公软件',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/shimo.svg',
        siteUrl: 'https://shimo.im/',
      },
      {
        title: '博思白板',
        desc: 'BoardMix在线协作白板，集思维导图，流程图、多维表格，笔记文档多种创意表达能力于一体，激发团队创造力无限延伸，免费在线使用。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/office/boardmix.svg',
        siteUrl: 'https://boardmix.cn/',
      },
    ],
  },
  {
    id: 18,
    label: 'Node 包管理',
    order: 16,
    icon: 'npm',
    children: [
      {
        title: 'npm',
        desc: 'node包管理器',
        logoUrl: getRoutePrefix() + '/dashboard/logo/npm/npm.svg',
        siteUrl: 'https://www.npmjs.com/',
      },
      {
        title: 'yarn',
        desc: 'Fast, reliable, and secure dependency management.',
        logoUrl: getRoutePrefix() + '/dashboard/logo/npm/yarn.svg',
        siteUrl: 'https://yarnpkg.com/',
      },
      {
        title: 'pnpm',
        desc: 'pnpm - 速度快、节省磁盘空间的软件包管理器',
        logoUrl: getRoutePrefix() + '/dashboard/logo/npm/pnpm.png',
        siteUrl: 'https://www.pnpm.cn/',
      },
    ],
  },
  {
    id: 19,
    label: '视频学习',
    order: 18,
    icon: 'learn',
    children: [
      {
        title: '慕课网',
        desc: '慕课网（IMOOC）是IT技能学习平台。慕课网(IMOOC)课程涉及JAVA、前端、Python、大数据等60类主流技术语言，覆盖了面试就业、职业成长、自我提升等需求场景，帮助用户实现从技能提升到岗位提升的能力闭环。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/learn/imooc.png',
        siteUrl: 'https://www.imooc.com/',
      },
      {
        title: '极客学院',
        desc: '极客学院作为专业IT职业在线教育平台,拥有海量高清IT职业课程,涵盖30+个技术领域。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/learn/jikexueyuan.png',
        siteUrl: 'https://www.jikexueyuan.com/',
      },
      {
        title: '哔哩哔哩',
        desc: 'bilibili是国内知名的视频弹幕网站，这里有及时的动漫新番，活跃的ACG氛围，有创意的Up主。大家可以在这里找到许多欢乐。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/learn/bilibili.svg',
        siteUrl: 'https://www.bilibili.com/',
      },
    ],
  },
  {
    id: 20,
    label: '面试刷题',
    order: 18,
    icon: 'leetcode',
    children: [
      {
        title: '大厂面试题每日一题',
        desc: '山月的全栈进阶之路',
        logoUrl: getRoutePrefix() + '/dashboard/logo/leetcode/shanyue.png',
        siteUrl: 'https://q.shanyue.tech/',
      },
      {
        title: '力扣（LeetCode）',
        desc: '备战技术面试？力扣提供海量技术面试资源，帮助你高效提升编程技能，轻松拿下世界 IT 名企 Dream Offer。',
        logoUrl: getRoutePrefix() + '/dashboard/logo/leetcode/leetcode.svg',
        siteUrl: 'https://leetcode.cn/',
      },
    ],
  },
];
